[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=d5bab521-4224-4a10-8cd5-53888057a8cf
Description=§RFB°T®§
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
SaveMousePos
LeftClick 1
MoveR 0, 300
Delay 100
LeftClick 1
MoveTo 1500, 640
Delay 100
LeftClick 1
Delay 100
RestoreMousePos
